"""Declarative base + shared metadata.

Schema is defined by Alembic migrations (source of truth = docs/contracts/data-model.md,
transcribed as raw DDL in migrations/). These ORM models mirror it for query/insert use.
Migrations are hand-authored (not blindly autogenerated) because of composite PKs,
partial/functional indexes, CHECK constraints, and deferred circular FKs.
"""

from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass
