"""Generate/check the reviewed FastAPI route inventory (ADR-045 O-13)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fastapi.routing import APIRoute

from app.main import app

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "contracts" / "route-inventory.md"
PUBLIC_PATHS = {
    "/health",
    "/readyz",
    "/meta",
    "/auth/login",
    "/connectors/gmail/oauth/callback",
    "/channels/email/webhook",
}


def _api_routes() -> list[APIRoute]:
    routes: list[APIRoute] = []
    for outer in app.routes:
        candidates = (
            outer.original_router.routes if type(outer).__name__ == "_IncludedRouter" else [outer]
        )
        routes.extend(route for route in candidates if isinstance(route, APIRoute))
    return routes


def _dependency_names(route: APIRoute) -> set[str]:
    names: set[str] = set()
    pending = list(route.dependant.dependencies)
    while pending:
        dependency = pending.pop()
        names.add(getattr(dependency.call, "__name__", str(dependency.call)))
        pending.extend(dependency.dependencies)
    return names


def render() -> str:
    rows: list[tuple[str, str, str, bool]] = []
    for route in _api_routes():
        dependencies = _dependency_names(route)
        auth = "public" if route.path in PUBLIC_PATHS else "session"
        csrf = "require_csrf" in dependencies
        for method in sorted((route.methods or set()) - {"HEAD", "OPTIONS"}):
            rows.append((route.path, method, auth, csrf))
    rows.sort(key=lambda row: (row[0], row[1]))
    lines = [
        "# Generated route inventory",
        "",
        "> Generated by `backend/scripts/route_inventory.py`; do not edit manually.",
        "",
        "| Method | Path | Auth | CSRF |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{method}` | `{path}` | `{auth}` | `{'yes' if csrf else 'no'}` |"
        for path, method, auth, csrf in rows
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                "route inventory is stale; run: "
                "cd backend && uv run python scripts/route_inventory.py",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
